### ISSUE TITLE
3D tiff to n5

### ISSUE THREAD

**Issue by orena1** [saalfeldlab/n5-spark#29]
Hi,
Maybe I'm missing it, but I could not find a way to convert a 3D (xyz) tiff to n5.
I did manage to do it with [bigstitcher](https://github.com/PreibischLab/BigStitcher), but the output `attributes.json`:
```
{"compression":{"type":"gzip","useZlib":false,"level":-1},"downsamplingFactors":[1,1,1],"blockSize":[128,128,64],"dataType":"uint16","dimensions":[2865,3792,32]}
```
is missing `"pixelResolution"` 

Any other tool to convert a tiff to n5 ? 
Thanks

**Comment by bogovicj** [comment]
Hi @orena1 ,

If your images are not too big, you can use the imagej plugins.
https://github.com/saalfeldlab/n5-ij/

**Comment by orena1** [comment]
Thanks
